"""Shared constants for the AI harness."""

import logging

logger = logging.getLogger(__name__)

DEFAULT_MODEL = "gemini-2.5-flash"
DEFAULT_AGENT_MODE = "auto"

# Curated subset of Claude Code's spinner verb list (random fallback).
# Upstream: references/claude-code-main/src/constants/spinnerVerbs.ts
SPINNER_VERBS: list[str] = [
    "Allocating",
    "Alphaing",
    "Architecting",
    "Baking",
    "Betaing",
    "Buffeting",
    "Bootstrapping",
    "Brewing",
    "Calculating",
    "Canoodling",
    "Cerebrating",
    "Churning",
    "Cogitating",
    "Coalescing",
    "Composing",
    "Computing",
    "Concentrating",
    "Concocting",
    "Contemplating",
    "Crafting",
    "Crunching",
    "Crystallizing",
    "Deciphering",
    "Deliberating",
    "Discombobulating",
    "Elucidating",
    "FatPitching",
    "FatTailing",
    "Fermenting",
    "Finagling",
    "Flywheeling",
    "Forging",
    "Gallivanting",
    "Generating",
    "Germinating",
    "Harmonizing",
    "Harvesting",
    "Hedging",
    "Hatching",
    "Ideating",
    "Imagining",
    "Inferring",
    "Manifesting",
    "Marinating",
    "Metamorphosing",
    "Mulling",
    "Mitigating",
    "Moating",
    "Musing",
    "Noodling",
    "Orchestrating",
    "Percolating",
    "Philosophising",
    "Pondering",
    "Pontificating",
    "Processing",
    "Puzzling",
    "Quantumizing",
    "Recombobulating",
    "Reticulating",
    "Ruminating",
    "Scampering",
    "Simmering",
    "Spelunking",
    "Sprouting",
    "Stewing",
    "Synthesizing",
    "Transmuting",
    "Vibing",
    "Waffling",
    "Whirring",
    "Wrangling",
]

_SPINNER_VERBS_SET: frozenset[str] = frozenset(SPINNER_VERBS)
